### ISSUE TITLE
Add Copy button to Network data

### ISSUE THREAD

**Issue by gndelia** [hemilabs/ui-monorepo#101]
In the `Manual` configuration of the network in the marketing page, the RPC and other information is shown like this 

![image](https://github.com/BVM-priv/ui-monorepo/assets/352474/766129a4-e0e1-469b-90fe-f61124f9364d)

Perhaps these could have a small copy button next to it, so the URL, chain Id, or whatever is easily copied.

**Comment by dvnahuel** [comment]
You can see the design [here](https://www.figma.com/design/4fVd9wneclsvYDYD95ApZ9/Hemi-Portal?node-id=3786-29265&t=xogSgcMmNP4SVorT-1)
