### ISSUE TITLE
Simple page for Hemispheres.xyz

### ISSUE THREAD

**Issue by philgomes** [hemilabs/ui-monorepo#104]
Jake and I are working on design/copy for a simple one-page site for the foundation that will sit at the hemispheres.xyz URL. Once we deliver the assets, how long will it take to tilt up? If we delivered by Mar. 7, could it be up by Mar. 8? 

@gndelia

**Comment by gndelia** [comment]
The main page is live at https://hemi.xyz/ - This issue is no longer needed (nor I think this is the correct repo). If anything is needed, let's open up a new issue in the appropriate repo.
