### ISSUE TITLE
Create / Authenticate hello@hemi.xyz

### ISSUE THREAD

**Issue by philgomes** [hemilabs/ui-monorepo#115]
From @esperrin12 --

Looking to get some help verifying the Hemi email sending domain. We need to do this in order to send out emails.
In Hubspot, I have it down as hello@hemi.network. Can someone verify if this is the correct email?

I also need someone who has access to help me authenticate it.

@daniel-bloq

**Comment by rmilrad** [comment]
Closing as complete
