### ISSUE TITLE
"MAX" Button Issue on Tunnel

### ISSUE THREAD

**Issue by jsorkin24** [hemilabs/ui-monorepo#150]
Bug Replication Steps:

1. Click on the MAX button.
2. Observe that the wallet balance displays .4 thETH.
3. Note that the action button remains disabled, despite having a balance.
4. Manually entering .39 into the field enables the button correctly.

![image](https://github.com/BVM-priv/ui-monorepo/assets/32560576/19dd4efd-a5b8-41f0-84c9-9fa857d3519b)
![image](https://github.com/BVM-priv/ui-monorepo/assets/32560576/bcadd2a4-0b19-4aea-8840-ae69b9c37ffd)

**Comment by rmilrad** [comment]
Closing - outdated issue
