### ISSUE TITLE
suggestion: alternate to Google reCAPTCHA: Cloudflare Turnstile

### ISSUE THREAD

**Issue by joshuasing** [hemilabs/ui-monorepo#189]
It appears Google reCAPTCHA is currently being used in `webapp` and `claim-tokens`.

Cloudflare Turnstile is a new CAPTCHA replacement which aims to deliver a frustration-free experience to real users, while preventing abuse as accurately and without a lot of the data privacy concerns associated with reCAPTCHA and hCaptcha.
https://www.cloudflare.com/en-au/products/turnstile/

I think Turnstile provides a better user experience, while still preventing the majority of bots, and as such could be a good replacement for reCAPTCHA.

**Comment by gndelia** [comment]
Closing as no longer valid (We're not using the claiming process anymore)
