### ISSUE TITLE
Uniswap link is unsafe

### ISSUE THREAD

**Issue by gndelia** [hemilabs/ui-monorepo#429]
it seems `swap.hemi.xyz` triggers some type of warning in google

![image](https://github.com/user-attachments/assets/2784eaf3-c346-403e-9594-612f5ba31f06)

![image](https://github.com/user-attachments/assets/1c222726-c18c-4254-8774-6b883394e2f9)

Hiding the link as requested by @rmilrad  until it is solved

**Comment by rmilrad** [comment]
@gndelia Can you please close? I have to update my permissions in this repo and currently dont have access.

**Comment by gndelia** [comment]
Created #442 to show the DEX again as this issue's been solved
