### ISSUE TITLE
Timestamp is missing in some withdrawals

### ISSUE THREAD

**Issue by gndelia** [hemilabs/ui-monorepo#432]
Sometimes the timestamp is missing in a withdrawal

![image](https://github.com/user-attachments/assets/ca2c6f5e-1c94-4fd6-a3ad-57a5e532e464)

The TX history should auto-recover from this

**Comment by rmilrad** [comment]
@gndelia I think this was solved? Can this be closed?

**Comment by gndelia** [comment]
Yes. Some users may still see them if the Chain was reorganized (it happened during the launch due to the heavy load), but for dropping those, we will use the option https://github.com/hemilabs/ui-monorepo/issues/440 to be develop.

Closing
