### ISSUE TITLE
Allow users to resync the Transaction history manually

### ISSUE THREAD

**Issue by gndelia** [hemilabs/ui-monorepo#440]
Under certain circumstances (Such as a chain reorg), a user may end up with operations in the TX-history that are no longer valid. We need to find a way to remove those operations from the history, as they add noise. One option is to resync everything, so invalid operations are automatically discarded.

**Comment by rmilrad** [comment]
@gndelia Do we need a bit of UI here to complete this issue? (cc @dvnahuel )

**Comment by gndelia** [comment]
yes, that's why Nahuel is assigned

**Comment by dvnahuel** [comment]
What I suggest and discussed with @gndelia is to add the 'Reload' CTA in the transaction history table. This will allow users to reload the items, and in doing so, the invalid operations will be automatically discarded. After the reload button is clicked, a toast notification will inform users that some of the items in the history may have disappeared, indicating they were invalid (text still WIP).

**Comment by gndelia** [comment]
@dvnahuel @rmilrad is "text sill WIP" as indicated in the last comment? Otherwise, I could take this issue

**Comment by dvnahuel** [comment]
> @dvnahuel @rmilrad is "text sill WIP" as indicated in the last comment? Otherwise, I could take this issue

Indeed! designs [here](https://www.figma.com/design/9A3yGxPovTEjn3OQ3Uterc/Hemi-Marketing?node-id=4529-6040&t=jPph30BDVqf77u0v-1)
