### ISSUE TITLE
Add tracking to portal 

### ISSUE THREAD

**Issue by rmilrad** [hemilabs/ui-monorepo#447]
Need to link with @dvnahuel to discuss what metrics we should be collecting from the portal app

**Comment by gndelia** [comment]
As part of this PR, we need to 

- Add to Github `vars` the Tracking URL (`NEXT_PUBLIC_ANALYTICS_URL`)
- Add the Website Id to GitHub secrets  (`NEXT_PUBLIC_ANALYTICS_WEBSITE_ID`)

I can ping either to provide the values


cc @dhidalgX @daniel-bloq
