### ISSUE TITLE
Portal onboarding ui updates

### ISSUE THREAD

**Issue by rmilrad** [hemilabs/ui-monorepo#451]
Need to update the claim process for Capsule with the following changes:

1. Remove the email capture, recaptcha, and email marketing from the UI
2. <img width="553" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk00Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d37c92ab62a40c3215c7ba7a2ee2e94ba043dce3/image.png" alt="image.png" />
Enlarge the claim button and route users to the general Hemi Discord: https://discord.gg/hemixyz
3. Add copy underneath the claim button that says "Join our Discord server and visit the **#claim-capsule** channel to claim a Capsule"

**Comment by gndelia** [comment]
Adding the image because I don't see it 
![image](https://github.com/user-attachments/assets/98bd8501-1026-4c5f-9d35-d92a02946efd)
