### ISSUE TITLE
Alert users that deposit/withdrawing bitcoin has a minimum of 0.01 btc

### ISSUE THREAD

**Issue by gndelia** [hemilabs/ui-monorepo#454]
Users can deposit/withdraw bitcoin, but the min amount is ~`0.005`~`0.01` - this is restricted at level contract. We need some warning/alert/info to the user prior to withdraw.
Deposits require a minimum of `0.01` tbc. 

We should also validate this before starting the deposit/withdraw to prevent invalid operations

**Comment by gndelia** [comment]
Deposits will now require `0.01` as a minimum to deposit as well

**Comment by dvnahuel** [comment]
To address this, I suggest setting the input placeholder to display the minimum allowed amount (0.01 BTC) to guide the user. Additionally, we can include a label just below the input field stating 'Minimum deposit is 0.01 BTC' to make the requirement clear upfront.
Designs [here](https://www.figma.com/design/4fVd9wneclsvYDYD95ApZ9/Hemi-Portal?node-id=7410-9794&t=79lDOFS8J45aUoXm-1)
Screenshot below
![Image](https://github.com/user-attachments/assets/ff4840a5-04a4-4d60-9436-5de8122cf871)
