### ISSUE TITLE
Allow customizing RPC urls per env variables

### ISSUE THREAD

**Issue by gndelia** [hemilabs/ui-monorepo#510]
The sepolia RPC is stuck and users can't see their balances updated. The RPC Url comes from the viem's chain definition. We need to provide a mechanism to override RPC URLs through env variables

**Comment by gndelia** [comment]
We need to add the following env variables:

- `NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA_PROD`:  `https://rpc2.sepolia.org`
- `NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA_STAGING`:  `https://rpc2.sepolia.org`

**Comment by daniel-bloq** [comment]
@gndelia Created!
![image](https://github.com/user-attachments/assets/a91afd74-217c-413a-832a-b0bbe63abdb0)

**Comment by gndelia** [comment]
Reopening as this issue will be closed once #511 is merged 😅

**Comment by gndelia** [comment]
Reopening as the current implementation fails with web workers 😞
