### ISSUE TITLE
Update Hemi RPC URL

### ISSUE THREAD

**Issue by gndelia** [hemilabs/ui-monorepo#543]
The RPC URL needs to be added to github variables, by setting

- `NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA_PROD`
- `NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA_STAGING`

**Comment by daniel-bloq** [comment]
Added to the repo's variables.

**Comment by gndelia** [comment]
Reopening (it will be closed after merging #545)
