### ISSUE TITLE
Add Youtube social icon into the social component in the navbar

### ISSUE THREAD

**Issue by dvnahuel** [hemilabs/ui-monorepo#561]
We need to add the youtube social link to our social component which is located in the navbar

Link: https://www.youtube.com/@HemiLabs
Designs: [here](https://www.figma.com/design/4fVd9wneclsvYDYD95ApZ9/Hemi-Portal?node-id=4256-45614&t=Kt271vu0YIBgLAQK-1)
Screenshot:
<img width="797" alt="Screenshot 2024-10-03 at 1 10 06 PM" src="https://github.com/user-attachments/assets/9f8972cf-375f-4c2c-ba8d-95c542d6ebc4">

**Comment by gndelia** [comment]
@rmilrad  should we add this to current app, or directly to the redesigned version?

**Comment by rmilrad** [comment]
@gndelia If its easy to add now, we can add it, otherwise we can add when we update the UI
