### ISSUE TITLE
Redesign tooltips components

### ISSUE THREAD

**Issue by dvnahuel** [hemilabs/ui-monorepo#580]
New tooltips componentes should be redesigned.
New tooltip designs: [here](https://www.figma.com/design/4fVd9wneclsvYDYD95ApZ9/Hemi-Portal?node-id=5407-15073&t=eKsOjCNhHqCdBLji-1)
Screenshot: ![Image](https://github.com/user-attachments/assets/2d4aa517-230b-4fe3-9503-bbed53357847)

**Comment by gndelia** [comment]
@dvnahuel should a green checkbox or something appear after clicking, confirming the success of the operation?

**Comment by dvnahuel** [comment]
Yep! ![Image](https://github.com/user-attachments/assets/dc29e636-e57a-4039-9b50-3df0a3659d55)
Designs [here](https://www.figma.com/design/4fVd9wneclsvYDYD95ApZ9/Hemi-Portal?node-id=6139-9237&t=eKsOjCNhHqCdBLji-1)
