### ISSUE TITLE
Wrong Network switch for Hemi Network

### ISSUE THREAD

**Issue by rmilrad** [hemilabs/ui-monorepo#682]
### Description

For some reason, the portal Wrong Network pop-up does not work properly when switching from Ethereum to Hemi mainnet. The same thing occurs on testnet when prompting a user to switch from Sepolia to Hemi Sepolia, there is some error that is occurring. 

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/40ddd07a-98a4-4c57-9efd-3a22349aa68c)
https://github.com/user-attachments/assets/39d7f753-2b9f-4ba9-808a-6033785f45b0

### Environment

- **OS**: Mac
- **Runtime/Browser/Version**: Chrome
- **Wallet**: Metamask

### Proposed fix

na

**Comment by gndelia** [comment]
These errors mean the RPC is failing. Once the RPC is stable and works, switching should automatically works

**Comment by gndelia** [comment]
@rmilrad  can we close this one? Seems to be working
