### ISSUE TITLE
Remove outdate 3d graphic

### ISSUE THREAD

**Issue by rmilrad** [hemilabs/ui-monorepo#684]
### Feature or change description

We can remove this 3d graphic from the portal, since it is no longer used on the Hemi website come mainnet.

### Problem or use case addressed

![Image](https://github.com/user-attachments/assets/9ec1c72e-7571-4241-96a9-ee12e10ef9fb)

### Proposed implementation

@dvnahuel can you please mock up something super simple, even just the removal of the visual, no other visual needed, for @gndelia to adjust the design with?

**Comment by dvnahuel** [comment]
New designs [here](https://www.figma.com/design/4fVd9wneclsvYDYD95ApZ9/Hemi-Portal?node-id=5407-14315&t=P1hf6WqSrri5EoBY-1)

Assets file:![Image](https://github.com/user-attachments/assets/36e88c8a-219d-4a5d-aaaa-56da66c13067)
![Image](https://github.com/user-attachments/assets/183b7549-e469-40e3-89c9-0a1c94ef1862)

Screenshot for reference:
<img width="794" alt="Image" src="https://github.com/user-attachments/assets/22232507-9bc9-4ff0-90cb-f1765f0278a3" />

cc: @gndelia
