### ISSUE TITLE
Change URL for swap

### ISSUE THREAD

**Issue by rmilrad** [hemilabs/ui-monorepo#686]
### Description

In the mainnet Get Started section of the Portal, we need to change the URL to the Sushi swap page instead of the Hemi swap page. URL still not defined but want to track here

![Image](https://github.com/user-attachments/assets/451a969e-ba20-42ae-bf25-27e00442690f)

**Comment by gndelia** [comment]
This is already tracked here https://github.com/hemilabs/ui-monorepo/issues/586
