### ISSUE TITLE
UI not showing tunneled ETH properly

### ISSUE THREAD

**Issue by gabmontes** [hemilabs/ui-monorepo#697]
### Description

@jcvernaleo tried to tunnel 0.1 mainnet ETH to Hemi using the portal and based on the explorer it went through, but the portal never seems to update. It just sits there looking like it didn't finish.

He said: Had me sign it with my ledger, all seemed good on that end and the funds made it to the address on Hemi.

![Image](https://github.com/user-attachments/assets/293aa5b7-5367-464b-999e-f724262c42fc)

### Environment

- **OS**: Linux
- **Runtime/Browser/Version**: Brave
- **Wallet**: Rabby

### Proposed fix

TBD

**Comment by jcvernaleo** [comment]
Probably related, in the `Review Deposit` window never changes from the Initial deposit showing as `Pending` despite the tx being confirmed on etherscan.

**Comment by gabmontes** [comment]
This was an RPC issue. Both staging and prod were updated with new RPC URL and the status of deposits now update properly.
