### ISSUE TITLE
Enable USDT/USDC tunneling for mainnet

### ISSUE THREAD

**Issue by gndelia** [hemilabs/ui-monorepo#709]
### Feature or change description

Per Matt, we won't be using the regular UI tunneling form for these 2 tokens, but we will provide a notification / method to show options for the user to select (initially, only Stargate). The user will click the desired link and be redirected to that page (links are TBD)

**Comment by dvnahuel** [comment]
https://github.com/hemilabs/ui-monorepo/issues/719#issue-2759076466

**Comment by gndelia** [comment]
Closing this (Superseded by the related issue ☝ )
